name: unsloth_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - debugpy=1.8.16=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - libkrb5=1.21.3=h520c7b4_4
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hd590300_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2025.0.0=hacee8c2_941
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py311h06a4308_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h49ec1c0_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py311h06a4308_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - tornado=6.5.2=py311h49ec1c0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.10.0
      - adal==1.2.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - airportsdata==20250622
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argcomplete==3.6.2
      - astor==0.8.1
      - attrs==25.3.0
      - azure-common==1.1.28
      - azure-core==1.35.0
      - azure-graphrbac==0.61.2
      - azure-mgmt-authorization==4.0.0
      - azure-mgmt-containerregistry==13.0.0
      - azure-mgmt-core==1.6.0
      - azure-mgmt-keyvault==11.0.0
      - azure-mgmt-network==29.0.0
      - azure-mgmt-resource==24.0.0
      - azure-mgmt-storage==23.0.0
      - azureml==0.2.7
      - azureml-core==1.60.0.post1
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==4.3.0
      - bitsandbytes==0.46.0
      - black==25.1.0
      - blake3==1.0.5
      - cachetools==6.1.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - compressed-tensors==0.10.1
      - contextlib2==21.6.0
      - contourpy==1.3.3
      - cryptography==45.0.6
      - cupy-cuda12x==13.4.1
      - cut-cross-entropy==25.1.1
      - cycler==0.12.1
      - datasets==3.6.0
      - depyf==0.18.0
      - diffusers==0.34.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker==7.1.0
      - docstring-parser==0.16
      - einops==0.8.1
      - email-validator==2.2.0
      - fastapi==0.115.13
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.19.1
      - flash-attn==2.8.3
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.7
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - interegular==0.3.3
      - ipython==9.3.0
      - isodate==0.7.2
      - jeepney==0.9.0
      - jiter==0.10.0
      - jmespath==1.0.1
      - jsonpickle==4.1.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - knack==0.12.0
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mistral-common==1.6.2
      - msal==1.33.0
      - msal-extensions==1.3.1
      - msgpack==1.1.1
      - msgspec==0.19.0
      - msrest==0.7.1
      - msrestazure==0.6.4.post1
      - multidict==6.5.1
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - ndg-httpsclient==0.5.1
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==2.2.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - openai==1.91.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-exporter-otlp-proto-http==1.34.1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opentelemetry-semantic-conventions-ai==0.4.9
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.3.0
      - paramiko==3.5.1
      - partial-json-parser==0.2.1.1.post6
      - pathspec==0.12.1
      - peft==0.15.2
      - pillow==11.2.1
      - pkginfo==1.12.1.2
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==5.29.5
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyjwt==2.10.1
      - pynacl==1.5.0
      - pyopenssl==25.1.0
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyzmq==27.0.0
      - ray==2.47.1
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rich-toolkit==0.14.7
      - rpds-py==0.25.1
      - safetensors==0.6.2
      - scienceplots==2.1.1
      - scipy==1.16.0
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.31.0
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - shtab==1.7.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.2
      - tabulate==0.9.0
      - tiktoken==0.9.0
      - tokenizer==3.5.1
      - tokenizers==0.22.1
      - torch==2.7.0
      - torchao==0.13.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - triton==3.3.0
      - trl==0.19.1
      - typeguard==4.4.4
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tyro==0.9.24
      - tzdata==2025.2
      - unsloth==2025.8.10
      - unsloth-zoo==2025.8.9
      - urllib3==2.5.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - vllm==0.9.1
      - wandb==0.20.1
      - watchfiles==1.1.0
      - websockets==15.0.1
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/azureuser/miniconda/envs/unsloth_env
