seed: 42

defaults:
   - override hydra/job_logging: default
   - override hydra/hydra_logging: default

model:
  checkpoint: 500
  name: "/mnt/pdata/caf83/tabular_reasoning/outputs/${wandb.run_name}/checkpoint-${model.checkpoint}" 
  max_prompt_length: 200
  max_completion_length: 824
  load_in_4bit: true
  fast_inference: true
  lora_rank: 128
  gpu_memory_utilization: 0.6
  
dataset:
  name: "countdown"   # Change to "gsm8k_kd" (or other) to switch datasets
  split: "test"

sampling:
  n_samples: 16
  temperature: 1
  top_p: 0.95

eval:
  ks : [1, 3, 5, 10]
  use_vllm: true
  per_device_eval_batch_size: 32
  report_to: "wandb"

wandb:
  project: "expert_reasoning"
  entity: eth_dlad_team32
  run_name: "countdown_grpo_3B"