seed: 42

defaults:
   - override hydra/job_logging: default
   - override hydra/hydra_logging: default

model:
  policy_name: "Qwen/Qwen2.5-3B-Instruct"
  reward_name: "Qwen/Qwen2.5-0.5B-Instruct" #Qwen/Qwen2.5-0.5B-Instruct
  max_seq_length: 1024
  load_in_4bit: true
  fast_inference: false
  
  # Common settings
  lora_rank: 64  # Base LoRA rank
  use_gradient_checkpointing: true
  
  # Policy model specific
  policy_lora_rank: 128  # Optional: override base rank for policy
  policy_learning_rate: 1e-5
  
  # Reward model specific  
  reward_lora_rank: 32  # Optional: override base rank for reward
  reward_learning_rate: 1e-4

  # Reward model settings
  use_outcome_rewards: false  # Use outcome rewards in addition to reward model
  reward_updates_per_policy_step: 10

dataset:
  name: "gsm8k_kd"
  split: "train"
  train_ratio: 0.1
  val_ratio: 0.01

training:
  # Common training params
  warmup_ratio: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.99
  weight_decay: 0.1
  lr_scheduler_type: "cosine"
  optim: "paged_adamw_8bit"
  logging_steps: 2
  max_grad_norm: 1.0
  output_dir: "/mnt/pdata/caf83/tabular_reasoning/outputs/${wandb.run_name}"
  report_to: "none"
  per_device_train_batch_size: 6
  gradient_accumulation_steps: 2
  max_steps: 100
  epochs: 2
  
sampling:
  temperature: 1.0
  top_p: 0.95
  num_generations: 6

eval:
  do_eval: true
  eval_strategy: "steps"
  eval_steps: 10
  per_device_eval_batch_size: 6
  eval_accumulation_steps: 2
  prediction_loss_only: false

wandb:
  project: "expert_reasoning"
  entity: eth_dlad_team32
  run_name: "irl_debug"