seed: 42
airl: true

defaults:
   - override hydra/job_logging: default
   - override hydra/hydra_logging: default

model:
  checkpoint: 500
  name: "/mnt/pdata/caf83/tabular_reasoning/outputs/${wandb.run_name}/checkpoint-${model.checkpoint}" 
  policy_name: "${model.name}"
  reward_name: "${model.name}/reward_model"
  lora_rank: 128
  gpu_memory_utilization: 0.6
  policy_gpu_memory_utilization: 0.6
  reward_gpu_memory_utilization: 0.15

  max_prompt_length: 300
  max_completion_length: 824
  load_in_4bit: true
  fast_inference: true
  
  # Policy model specific
  policy_lora_rank: 128  # Optional: override base rank for policy
  policy_learning_rate: 1e-5

  # Reward model specific  
  reward_lora_rank: 32  # Optional: override base rank for reward
  dense_rewards: true  # Whether to use dense rewards (token-level) or sparse (sequence-level)
  dense_gamma: 0.9

  
dataset:
  name: "gsm8k_kd"   # Change to "gsm8k_kd" (or other) to switch datasets
  split: "test"

sampling:
  n_samples: 16
  temperature: 1
  top_p: 0.95

eval:
  ks : [1, 3, 5, 10]
  use_vllm: true
  per_device_eval_batch_size: 5
  report_to: "none"

wandb:
  project: "expert_reasoning"
  entity: eth_dlad_team32
  run_name: airl_per_wgan_099