seed: 42

defaults:
   - override hydra/job_logging: default
   - override hydra/hydra_logging: default

model:
  name: "meta-llama/Llama-3.2-3B-Instruct"  #"microsoft/Phi-4-mini-instruct", "google/gemma-3-4b-it", "meta-llama/Llama-3.2-3B-Instruct. "Qwen/Qwen2.5-3B-Instruct"
  max_prompt_length: 300
  max_completion_length: 824
  load_in_4bit: true
  fast_inference: true
  lora_rank: 128
  gpu_memory_utilization: 0.6
  
dataset:
  name: "gsm8k_kd"   # Change to "gsm8k_kd" (or other) to switch datasets
  split: "train"
  train_ratio: 1.0
  val_ratio: 0.1

training:
  learning_rate: 1e-5
  adam_beta1: 0.9
  adam_beta2: 0.99
  weight_decay: 0.1
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  optim: "paged_adamw_8bit"
  logging_steps: 10
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 2
  num_generations: 16
  epochs: 2
  max_steps: 500
  max_grad_norm: 1.0
  output_dir: "/mnt/pdata/caf83/tabular_reasoning/outputs/${wandb.run_name}"
  report_to: "wandb"
  

sampling:
  temperature: 1
  top_p: 0.95

eval:
  do_eval: true
  eval_strategy: "steps"
  eval_steps: 100
  use_vllm: true
  per_device_eval_batch_size: 16
  eval_accumulation_steps: 2
  prediction_loss_only: false

wandb:
  project: "expert_reasoning"
  entity: eth_dlad_team32
  run_name: llama3_sft